name: Run tests

on: push

jobs:

  static_check:
    runs-on: ubuntu-18.04
    steps: 
    - name: Check out code
      uses: actions/checkout@v2

    - name: Shell script static cheking
      uses: ludeeus/action-shellcheck@master
      with:
        severity: info


  build:
    runs-on: ubuntu-18.04
    needs: static_check
    strategy:
      matrix:
        mongodb-version: [4.2.16, 4.4.9, 5.0.3]

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Export env variables
      run: |
        echo "UBUNTU_VERSION=linux-x86_64-ubuntu$(lsb_release -r | tr -d '[:alpha:][:blank:][:punct:]')" >> $GITHUB_ENV
        echo "MONGO_VERSION=$( echo ${{ matrix.mongodb-version }} | tr -d '[:alpha:][=-=]')" >> $GITHUB_ENV

    - name: Download MongoDB
      run: |
        wget -q http://downloads.mongodb.org/linux/mongodb-$UBUNTU_VERSION-$MONGO_VERSION.tgz
        tar xzvf mongodb-$UBUNTU_VERSION-$MONGO_VERSION.tgz
        echo "$PWD/mongodb-$UBUNTU_VERSION-$MONGO_VERSION/bin" >> $GITHUB_PATH

    - name: Create DB dir and launch cluster
      run: |
        mkdir -p /home/runner/data/db
        ./deploy.sh /home/runner/data/db 2
    
    - name: Check result and make sure all shards are up
      run: |
        cat result.txt
        grep shardRs1 result.txt
        grep shardRs2 result.txt